/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package towerOfHanoi;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static java.time.Duration.ofMinutes;

import java.util.ArrayList;

class HanoiSolverTest {
    @Test void def() {
        assert (1==1);
    }
}
